name: notion_versioning

inputs:
  version:
    required: true
  api_key:
    required: true

runs:
  using: composite
  steps:
    - id: get-current-date
      shell: bash
      run: |
        sudo timedatectl set-timezone Asia/Seoul
        echo "date=$(date +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_OUTPUT

    - name: Use Notion API
      shell: bash
      run: |
        curl -X POST 'https://api.notion.com/v1/pages' \
          -H 'Authorization: Bearer ${{ inputs.api_key }}' \
          -H "Content-Type: application/json" \
          -H "Notion-Version: 2022-06-28" \
          --data '{
            "parent": {
              "database_id": "16d02394dc4245ec969b1536dc88439c"
            },
            "properties": {
              "배포 상태": {
                "status": {
                  "name": "완료"
                }
              },
              "배포 일시": {
                "date": {
                  "start": "${{ steps.get-current-date.outputs.date }}",
                  "time_zone": "Asia/Seoul"
                }
              },
              "개정 버전": {
                "title": [
                  {
                    "type": "text",
                    "text": {
                      "content": "${{ inputs.version }}"
                    }
                  }
                ]
              }
            }
          }'
